version: 2

updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "0 0 * * 0"
  versioning-strategy: "increase-if-necessary"
  ignore:
  - dependency-name: "@types/node"
    update-types: ["version-update:semver-major"]
